name: ski-analysis-paper
channels:
  - conda-forge
dependencies:
  - cython ==0.29.21
  - dash ==1.18.1
  - matplotlib ==3.3.3
  - numpy ==1.19.5
  - pandas ==1.2.0
  - python ==3.9.1
  - scipy ==1.6.0
  - skijumpdesign ==1.4.0
  - sympy ==1.7.1
  - xlrd ==2.0.1
